language: rust
cache: cargo
services:
  - mysql
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta

before_script:
  - cargo install diesel_cli cargo-make
  - cargo make setup-db
script:
  - cargo test
