language: rust
cache: cargo
env:
  - DATABASE_URL=mysql://localhost/testament TEST_DATABASE_URL=mysql://localhost/testament_test
services:
  - mysql
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta

before_script:
  - cargo install --force diesel_cli cargo-make
  - cp .env.sample .env
  - cargo make setup-db --env-file=.env
script:
  - bash -c '[[ "TRAVIS_RUST_VERSION" == "nightly" || cargo build'
  - cargo make test
