language: rust
cache: cargo
services:
  - mysql
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta

before_script:
  - cargo install diesel_cli cargo-make || echo ""
  - cp .env.sample .env
  - cargo make setup-db --env-file=.env
script:
  - cargo test
