[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--"]

[tasks.setup-db-test]
command = "diesel"
args = ["setup", "--config-file", ".env.test"]

[tasks.setup-db-dev]
command = "diesel"
args = ["setup", "--config-file", ".env"]

[tasks.setup-db]
dependencies = [
	"setup-db-dev",
	"setup-db-test"
]

[tasks.migration-test]
command = "diesel"
args = ["migration", "run", "--config-file", ".env.test"]

[tasks.migration-dev]
command = "diesel"
args = ["migration", "run", "--config-file", ".env"]

[tasks.migration]
dependencies = [
	"migration-dev",
	"migration-test"
]

[tasks.generate-schema]
command = "diesel"
args = ["print-schema", "--config-file", ".env", ">", "src/schema.rs"]

[tasks.setup]
dependencies = [
    "format",
		"setup-db",
		"migration",
		"generate-schema"
]
